name: Publish to GCloud App Engine

on:
  push:
    branches:
      master

jobs:
  publish-gae:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - uses: actions/gcloud/auth@master
          env:
            GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
            GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      - uses: actions/gcloud/cli@master
        with:
          args: "app deploy --quiet"
