name: Publish to Firebase

on:
  push:
    branches:
      master

jobs:
  publish-fb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Functions Dependencies
        run: cd firebase/functions && npm install && cd ../../
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: "deploy"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
