name: Publish to GCloud App Engine

on:
  push:
    branches:
      master

jobs:
  publish-gae:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
        with:
          args: "app deploy --quiet"
