name: Publish to GCloud App Engine

on:
  push:
    branches:
      master

jobs:
  publish-gae:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Copy secrets
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_SM_AUTH}}
        with:
          args: "secrets versions access latest --secret=App_Engine_Environment_Variables | tee .env"
      - name: Deploy to GAE
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
        with:
          args: "app deploy --quiet"
