name: Publish to GCloud App Engine

on:
  push:
    branches:
      master

jobs:
  publish-gae:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: secrets
        uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
        with:
          credentials: ${{ secrets.gcp_credentials }}
          secrets: |-
            vars: projects/585363008583/secrets/App_Engine_Environment_Variables
      - id: copy
        - run: echo ${{ steps.secrets.outputs.vars }} > .env
        - run: cat .env
#      - id: deploys
#        uses: actions-hub/gcloud@master
#        env:
#          PROJECT_ID: ${{secrets.GCLOUD_PROJECT}}
#          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
#        with:
#          args: "app deploy --quiet"
